### ISSUE TITLE
Running mvn clean install in intellij gives error

### ISSUE THREAD

**Issue by zeesh49** [GrahamLea/scala-spring-hibernate-maven-webapp#6]
Hi, my OS is ubuntu, I get the following error when I run mvn clean install. As you can see, I have changed the package names. Please help.

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.372 sec <<< FAILURE! - in com.SMS.webtest.ServerNamePageWebTest
shouldShowTheServerName(com.SMS.webtest.ServerNamePageWebTest)  Time elapsed: 0.008 sec  <<< ERROR!
java.lang.ExceptionInInitializerError: null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:754)
        at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:124)
        at org.openqa.selenium.firefox.GeckoDriverService.access$100(GeckoDriverService.java:41)
        at org.openqa.selenium.firefox.GeckoDriverService$Builder.findDefaultExecutable(GeckoDriverService.java:141)
        at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:339)
        at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:158)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:98)
        at com.SMS.webtest.WebDriverAccess$.<init>(WebDriverAccess.scala:30)
        at com.SMS.webtest.WebDriverAccess$.<clinit>(WebDriverAccess.scala)
        at com.SMS.webtest.WebDriverAccess$class.$init$(WebDriverAccess.scala:20)
        at com.SMS.webtest.ServerNamePageWebTest.<init>(ServerNamePageWebTest.scala:20)

**Comment by GrahamLea** [comment]
Sorry, but that code is over 3 years old now, though, in theory, it should “just work” because the man dependencies are versioned.

Try doing it on the command line instead of in IDEA. If that doesn’t work, I’m sorry, but you’ll have to figure it out yourself.

Cheers,

Graham.
